name: Continuous Build

on:
  push:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

env:
  TARGET_NODE_VERSION: '16.17.0'

jobs:
  documentation:
    name: Check documentation
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Check hyperlinks
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          config-file: .github/workflows/mlc_config.json

  lint-compile:
    name: Lint, Build
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.TARGET_NODE_VERSION }}
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn lint
      - name: Compile
        run: yarn compile

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    # Don't run twice for a push within an internal PR
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.TARGET_NODE_VERSION }}
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Unit test
        run: yarn test

  e2e-tests:
    name: E2E test
    runs-on: ubuntu-latest
    # Don't run twice for a push within an internal PR
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.TARGET_NODE_VERSION }}
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Run testing services
        run: yarn dev:background
      - name: Test E2E
        run: yarn test:e2e

  required-checks-passed:
    name: All required checks passed
    runs-on: ubuntu-latest
    needs: [documentation, lint-compile, unit-tests, e2e-tests]
    steps:
      - run: exit 0
